name: CI/CD Vercel

env:
  CI: false #TODO MM: Remove when dependencies are fixed
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID }}

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "*"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  Deploy-to-Development:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      # TODO MM: Implement semanti-release or something similar
    